### ISSUE TITLE
Feature request: add support of ecp over MQTT

### ISSUE THREAD

**Issue by ai91** [goecharger/go-eController-API#12]
As found out in https://github.com/goecharger/go-eController-API/issues/7, the _ecp_ API key is supported over local HTTP API only. 
Unfortunately it isn't accepted via MQTT (firmware 1.0.6 returns result `api key is not allowed from mqtt`).

Due to security issues (see https://github.com/goecharger/go-eController-API/issues/10) we can't activate local HTTP API. 

Feature request: please add _ecp_ support over MQTT.

**Comment by CommanderRedYT** [comment]
Can you try updating to a newer firmware? This should be implemented in release 1.0.9.

**Comment by erxbout** [comment]
Setting ecp over mqtt is supported since firmware version 1.0.8
So an update should fix your issue

**Comment by erxbout** [comment]
@ai91 bump
