### ISSUE TITLE
Data Export not working (domain down?)

### ISSUE THREAD

**Issue by SvenAbels** [goecharger/go-eController-API#8]
Hi,

when clicking the "download data" button in the app, an error message is displayed. The request goes to the following URL, which seems to be unavailable as its subdomain cannot be resolved:

https://data.controller.go-e.io/export?e=f2Ot......

**Comment by erxbout** [comment]
Is this still a problem?
At the moment I can not reproduce it..

**Comment by SvenAbels** [comment]
No. The server is back onlone
